// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IIc:sharpEmail': typeof import('~icons/ic/sharp-email')['default']
    'ILineMd:account': typeof import('~icons/line-md/account')['default']
    'IMaterialSymbols:lockSharp': typeof import('~icons/material-symbols/lock-sharp')['default']
    'IMdi:account': typeof import('~icons/mdi/account')['default']
    'IUiw:aliwangwang': typeof import('~icons/uiw/aliwangwang')['default']
    'IUiw:android': typeof import('~icons/uiw/android')['default']
    'IUiw:apple': typeof import('~icons/uiw/apple')['default']
    'IUiw:qq': typeof import('~icons/uiw/qq')['default']
    LoadingButton: typeof import('./src/components/loadingButton/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    NavBar: typeof import('./src/components/navBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
