// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bread: typeof import('./src/components/BreadeCrumbs/components/Bread.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs/index.vue')['default']
    BreadeCrumbs: typeof import('./src/components/BreadeCrumbs/index.vue')['default']
    BreadItem: typeof import('./src/components/BreadeCrumbs/components/BreadItem.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    'IIc:sharpEmail': typeof import('~icons/ic/sharp-email')['default']
    'ILineMd:account': typeof import('~icons/line-md/account')['default']
    'IMaterialSymbols:lockSharp': typeof import('~icons/material-symbols/lock-sharp')['default']
    'IMdi:account': typeof import('~icons/mdi/account')['default']
    Inex: typeof import('./src/components/Breadcrumbs/inex.vue')['default']
    'IUiw:aliwangwang': typeof import('~icons/uiw/aliwangwang')['default']
    'IUiw:android': typeof import('~icons/uiw/android')['default']
    'IUiw:apple': typeof import('~icons/uiw/apple')['default']
    'IUiw:qq': typeof import('~icons/uiw/qq')['default']
    LoadingButton: typeof import('./src/components/LoadingButton/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
